osx_image: xcode9
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_PROJECT=Keep/KeepGuidePage.xcodeproj
  matrix:
    - SCHEME="KeepGuidePage"
    
after_success:
  - sleep 5
